# Generated by Django 4.1.7 on 2023-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichiercsv',
            name='nom',
            field=models.CharField(default='mec', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
