# Generated by Django 4.1.7 on 2023-07-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_fichiercsv_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichiercsv',
            name='nom',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
